### ISSUE TITLE
Support for ES6 Modules?

### ISSUE THREAD

**Issue by DenisCarriere** [NickCis/polygonize#3]
Trying to convert TurfJS to ES modules, would it be possible to support ES modules in this library?

Also we're releasing v5.0, so might be a good idea to sync up the dependencies.

I can internalize this library into TurfJS for now until this library gets updated to ES modules.

**Comment by NickCis** [comment]
I'll be working in this issue in this [PR](https://github.com/NickCis/polygonize/pull/4).

If you like, you can review it.

@DenisCarriere as regards dependencies, should I upgrade to turf v5.0? (Although it hasn't been released yet)
